OfficeDev/office-scripts-docs

docs/toc.yml
docs/tutorials/excel-office-scripts-tutorial.md

This API is no longer "maker-safe".

Removing workbook.functions from tutorial

---

Issue_Template.md
README.md
docs/develop/scripting-fundamentals.md
docs/index.md
docs/overview/code-editor-environment.md
docs/overview/excel.md
docs/testing/troubleshooting.md

This PR adds some explanation as to why you'd choose Office Scripts, as well as adding more independence to the doc set by broadening the audience slightly.

Softening introductions on several pages

---

docs/tutorials/excel-tutorial.md

* Remove link to admin docs
* Incorporating note into sentence

Merge to live

---

docs/docfx.json
docs/resources/excel-samples.md

This PR also retools the samples page a bit by categorizing the samples.

Adding single cell and conditional formatting samples

---

docs/docfx.json
docs/index.md
docs/resources/excel-samples.md
docs/testing/undo.md
docs/tutorials/excel-tutorial.md

clean up tutorial
improve metadata
clarify admin enabling scope
add samples

Merge to live!

---

docs/develop/javascript-libraries.md
docs/develop/javascript-objects.md
docs/develop/scripting-fundamentals.md
docs/overview/code-editor-environment.md
docs/overview/excel.md
docs/resources/excel-samples.md
docs/toc.yml
docs/tutorials/excel-tutorial.md

The article focuses on Array, Date, and Math. The purpose is to show how these standard objects can help new script developers,

Adding an article and samples around standard JavaScript objects

---

docs/index.md

This fixes the reference doc link and adds hrefs to the first three icons.

Fixing index page links

---

docs/overview/excel.md

This PR introduces the integration with Power Automate in the overview page.  This helps set the "why" context for PA with Office Scripts.

Adding Power Automate section to overview page

---

docs/develop/scripting-fundamentals.md
docs/overview/excel.md
docs/tutorials/excel-read-tutorial.md
docs/tutorials/excel-tutorial.md

Articles that have been assigned `localization_priority: Priority` include:
- main landing page
- all tutorials
- other strategic/important content (e.g., overview & scripting fundamentals)

[Admin] (loc priority) Update value of localization_priority metadata attribute.

---

docs/overview/excel.md

[Staging site link](https://review.docs.microsoft.com/en-us/office/dev/scripts/overview/excel?branch=AlexJ-Video)

Switching out a video for the intro gif

---

docs/develop/javascript-objects.md
docs/resources/excel-samples.md

This PR adds a sample showing how to convert an Excel date to a JS date.

Read date sample

---

docs/develop/scripting-fundamentals.md

Switch rows and columns

---

docs/develop/scripting-fundamentals.md

Fixes #103.
This PR adds a more thorough explanation of how certain methods work in the async (load/sync) scripting model. It discusses the `ClientResult` object and when its values get loaded.

Discussion of ClientResults

---

docs/resources/scenarios/task-reminders.md
docs/tutorials/excel-power-automate-manual.md
docs/tutorials/excel-power-automate-trigger.md

While Office Scripts is still in preview, the connector will be available through GA Power Automate. We can know use the default PA service.

Remove preview prefix from Power Automate content

---

docs/resources/excel-samples.md
docs/resources/scenarios/analyze-web-downloads.md

This were inspired by sample suggestions provided by @sumurthy. 
I'll make the related reference doc PR after these are reviewed.

Adding more basic samples

---

docs/develop/excel-async-model.md

Scripts are stuck with the object model (async or sync) with which they are created. This PR corrects the article to better reflect that reality. It also gives some light guidance about converting your script from async to sync.

Clarification about async access

---

docs/resources/scenarios/analyze-web-downloads.md

[Staging site link](https://review.docs.microsoft.com/en-us/office/dev/scripts/resources/scenarios/analyze-web-downloads?branch=AlexJ-OldModelVideo#demo-video).
This note tried to reconcile the differences between the code shown in @jedunn's video and the code displayed on the page. I think that because the specifics of the code aren't the highlight of the video, it's okay to keep it with this caveat. Thoughts?

Add note about demo video async code

---

docs/resources/scenarios/analyze-web-downloads.md

Add note about demo video async code (#128)

[admin] Merge to live!

---

docs/develop/power-automate-integration.md
docs/overview/excel.md
docs/resources/vba-differences.md
docs/toc.yml
docs/tutorials/excel-power-automate-manual.md
docs/tutorials/excel-power-automate-trigger.md

The term "integrate" has [specific marketing meaning](https://microsoft.sharepoint.com/sites/celaweb-marketing/sitepages/marketing-and-advertising-content-red-flag-terms.aspx?xsdata=MDR8MDF8UGV0cmEuUm9uYWxkQG1pY3Jvc29mdC5jb218YTY1MzFlY2VhNTA0NDIxMTIyYjgwOGQ4MTkzY2ExMDB8NzJmOTg4YmY4NmYxNDFhZjkxYWIyZDdjZDAxMWRiNDd8MXwwfDYzNzI4NzA5NTQ5ODcyMDYyMXxVbmtub3dufFRXRnBiR1pzYjNkOGV5SldJam9pTUM0d0xqQXdNREFpTENKUUlqb2lWMmx1TXpJaUxDSkJUaUk2SWsxaGFXd2lMQ0pYVkNJNk1uMD18LTE%3D&sdata=OE5ZZDNXNHNUd3lZWGREQ0R0OWo5eUp3cnhkNERwSlJSWEo0V2lxVGg0OD0%3D), so this PR remove the use of the word.

Avoid the use of 'integrate'

---

docs/toc.yml

Adding page to TOC

---

docs/develop/power-automate-integration.md
docs/overview/excel.md
docs/resources/scenarios/sample-scenario-overview.md
docs/tutorials/excel-power-automate-manual.md
docs/tutorials/excel-power-automate-trigger.md
docs/tutorials/excel-read-tutorial.md

Tagging @ElizabethSamuel-MSFT for a general review and @gergzk for the "why use the product" lines he suggested.

Fixes suggested during the docs bash

---

docs/overview/code-editor-environment.md
docs/resources/scenarios/analyze-web-downloads.md

Tagging @ElizabethSamuel-MSFT for the writer review and @peronald to confirm the accuracy of the IE11 statement.

IE11 Support - Note and sample fixes

---

docs/develop/power-automate-integration.md
docs/includes/power-automate-tutorial-prerequisites.md
docs/includes/tutorial-prerequisites.md
docs/toc.yml
docs/tutorials/excel-power-automate-manual.md
docs/tutorials/excel-power-automate-trigger.md

The titles of the two Power Automate tutorials are too similar. This should address that concern.

IA for Power Automate tutorials

---

docs/develop/javascript-objects.md
docs/resources/excel-samples.md

This adds a couple samples about iterating over ranges and collections.

Adding more samples

---

docs/testing/troubleshooting.md

This PR documents the limitations of the platform and gives some guidance to work around potential problems.
@mscharlock for content review.
@danielgwilson for PA limits confirmation.
@sumurthy for Excel limits confirmation.

Recording data limits in Office Scripts

---

docs/overview/code-editor-environment.md
docs/testing/platform-limits.md
docs/testing/troubleshooting.md
docs/toc.yml

This PR adds information about the requirement of 3rd party cookies for scripts. It also restructures the docs a bit to create an article all about all the limits, so those can be found in one place.

Third-party cookies and IA

---

docs/docfx.json

[Preview site](https://review.docs.microsoft.com/en-us/office/dev/scripts/?branch=elizs-l2)

[Admin] (header) Add L2

---

docs/resources/excel-samples.md

This PR adds some samples related to formulas. One shows a basic formula scenario. The error deals with error-checking a spilled range.
There's also one that shows a common pattern around checking for null objects in collections.

Add collection and formula-related samples

---

docs/develop/excel-async-model.md
docs/includes/async-reference-documentation-link.md
docs/resources/add-ins-differences.md
docs/tutorials/excel-power-automate-trigger.md

[Example build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C1%5C918d1c35-f3a4-631b-1edf-a1a2af22eee5%5CPullRequest%5C202009011825117618-164%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nKctOeYw6wogycL3KyGpop2dxtMXJBZdwNDjAvtEji4%3D&st=2020-09-01T18%3A20%3A42Z&se=2020-10-02T18%3A25%3A42Z&sp=r)

[Admin] Fix build suggestions

---

docs/includes/teams-support-note.md
docs/overview/excel.md
docs/testing/platform-limits.md
docs/testing/troubleshooting.md

Adding a note for the current Office Scripts support story around Teams.

Teams support note

---

docs/testing/platform-limits.md

* Adding links to browser support pages about third-party cookie settings
* Remove extraneous link:

Merging to live

---

docs/resources/vba-differences.md

Clarifying auth token restrictions

---

docs/resources/scenarios/analyze-web-downloads.md

There was an error in the variable name that sets the conditional formatting of FALSE in "function applyConditionalFormatting", so I suggest fixing it.

There is a bug in the script

---

docs/resources/scenarios/analyze-web-downloads.md

There was an error in the variable name that sets the conditional formatting of FALSE in "function applyConditionalFormatting", so I suggest fixing it.

There is a bug in the script (#178)

---

docs/resources/scenarios/task-reminders.md
docs/tutorials/excel-power-automate-manual.md
docs/tutorials/excel-power-automate-trigger.md

Fixes #191.
This also adjusts one of the scripts to adapt to the newly return value types with ranges (by calling `toString` since the type is now `string | number | boolean`).

Adding note about PA file browser

---

docs/resources/excel-samples.md
docs/resources/scenarios/analyze-web-downloads.md
docs/resources/scenarios/grade-calculator.md

`getValues` no longer returns an `any[][]`, so casts need to be made in some of the samples.

Account for getValues() breaking API change

---

docs/resources/excel-samples.md

This sample shows a basic use case for the `getSpecialCells` API. It also fixes a header issue in the same page.

Add getSpecialCells sample

---

docs/develop/web-client-performance.md

Monthly link cleanup.  cc / @ElizabethSamuel-MSFT

Links: Office Scripts (2021-01)

---

README.md

We can revisit the validity after some audience investigation.

Remove dev program recommendation

---

docs/testing/platform-limits.md

Linking to more sources of Power Automate platform limits.

Add link to Excel Online (Business) connector limits

---

Contributing.md
Issue_Template.md
README.md
docs/docfx.json
docs/index.md

This PR redirects the reference to UserVoice to Microsoft Q&A for feature requests.

Remove UserVoice references

---

docs/resources/samples/getting-started.md

@AlexJerabek What do you think about doing something like this for files that would confuse SEO? This metadata should prevent the article from being indexed by search. I'm particularly thinking of the sample files we're still working through, especially if there may be duplicate content.

Hide from search

---

docs/resources/scenarios/noaa-data-fetch.md

This sample was not compatible with the new linter rules around implicit `any`. These changes should addres that.

Remove implicit any from NOAA sample

---

docs/resources/samples/samples-overview.md

This sample is cool, but relies on third-party files. I'm not sure we should include the source code in our docs for that reason. I feel like linking to the Tech Community blog is a good compromise.

Add Yutao's Game of Life sample as a link

---

docs/resources/samples/excel-cross-reference.md
docs/resources/samples/samples-overview.md
docs/toc.yml

These two samples require Power Automate integration. I'll add them back to the TOC and sample list once those steps are added.

[samples] Removing samples that don't have PA steps

---

docs/develop/external-calls.md
docs/overview/code-editor-environment.md
docs/testing/undo.md

Cookies, local storage, session storage

Add unsupported ext. calls scenarios

---

docs/overview/script-storage.md

This flight will likely not be pushed out to Production

Remove reference to "script folders"

---

docs/develop/external-calls.md

Grammar fix and changed excel client to excel application.

Jayrathi patch 4

---

docs/develop/excel-async-model.md
docs/develop/external-calls.md
docs/develop/javascript-objects.md
docs/develop/power-automate-integration.md
docs/develop/scripting-fundamentals.md
docs/develop/web-client-performance.md
docs/resources/samples/add-image-to-workbook.md
docs/resources/samples/excel-samples.md
docs/testing/platform-limits.md
docs/testing/power-automate-troubleshooting.md
docs/testing/troubleshooting.md
docs/tutorials/excel-power-automate-manual.md
docs/tutorials/excel-power-automate-trigger.md

Checked headings for consistency (Apply MSTP rule about not using the gerund form of the verb if it's the first word in a heading)
Updated SO link to Q&A
Minor edits

Lindalu bug bash finds

---

docs/resources/vba-differences.md

[Power Automate] Increasing PA visibility from VBA differences doc

---

docs/resources/samples/add-image-to-workbook.md

Thanks to @davidchesnut for finding this problem in https://github.com/OfficeDev/office-scripts-docs-reference/pull/111

[sample] Correct the image link

---

docs/testing/power-automate-troubleshooting.md

Internal work item: https://office.visualstudio.com/OC/_workitems/edit/5117543/
Data refresh methods do nothing when run in Power Automate. This PR documents that behavior.

[Power Automate] Explaining the lack of data refresh support in PA

---

docs/develop/external-calls.md

[external calls] Removing preview support notes about external calls

---

docs/overview/excel.md

[Script sharing] Rephrasing sharing intro

---

docs/overview/script-storage.md
docs/resources/vba-differences.md

[admin controls] Documenting more admin capabilities

---

docs/develop/scripting-fundamentals.md

This takes tip 2 from https://github.com/OfficeDev/office-scripts-docs/pull/248 and inserts it into the Scripting Fundamentals article.

[ranges] Adding type assertion tip

---

docs/develop/scripting-fundamentals.md
docs/includes/preview-note.md
docs/index.md
docs/overview/code-editor-environment.md
docs/overview/excel.md
docs/resources/samples/samples-overview.md

Removing the preview tags from the Office Scripts docs as we prepare for GA. Also correcting an incorrect include comment.

[Availability] Remove preview tags

---

docs/tutorials/excel-tutorial.md

* Adding further troubleshooting advice in the tutorial
* Update docs/tutorials/excel-tutorial.md
Co-authored-by: Alison McKay <almckay@microsoft.com>
Co-authored-by: Alison McKay <almckay@microsoft.com>

[admin] Publish

---

docs/overview/code-editor-environment.md

* Adding IntelliSense tips
* Update docs/overview/code-editor-environment.md
Co-authored-by: Alison McKay <almckay@microsoft.com>
Co-authored-by: Alison McKay <almckay@microsoft.com>

[admin] (Publish)

---

docs/develop/best-practices.md
docs/resources/samples/automate-tasks-on-all-excel-files-in-folder.md
docs/resources/samples/email-images-chart-table.md
docs/resources/samples/excel-cross-reference.md

According to the MSFT style guide, the sentence preceding a list should end with a period (not a colon) unless it is a fragment. This PR applies that standard across the samples.

[style] Standardized pre-list punctuation

---

docs/overview/excel.md
docs/overview/script-storage.md
docs/resources/samples/excel-calculation.md
docs/testing/platform-limits.md
docs/tutorials/excel-power-automate-returns.md

Based on @Soran-M's guidance to remove the English title from SOC links and only use the GUID.

[admin] (Links) Fix SOC links to match to loc guidance

---

docs/resources/samples/combine-worksheets-into-single-workbook.md

Fixes #400. 
It's easy to miss the note explaining this Power Automate button. This PR changes the sample text to better draw attention to the required step.

[samples] (Combine workbooks) Make the need to switch the input more clear

---

docs/testing/platform-limits.md

Change is finally rolled out to all stations https://msazure.visualstudio.com/One/_workitems/edit/10538123/

Update 400 -> 800 quota change

---

docs/testing/platform-limits.md

Updating the one link anchor to a field in an API reference doc.

[admin] (Links) Update link anchors

---

docs/includes/preview-note.md
docs/includes/rollout-note.md
docs/includes/run-from-button-desktop-support.md
docs/overview/excel.md
docs/resources/add-ins-differences.md
docs/resources/vba-differences.md

Excel for the web features are rolled out to a percentage of customers to ensure they meet reliability requirements. The term "preview" was a misnomer, as features that are ready for general availability are still partially available for periods of time. This PR better explains that process.

[availability] (pre-release) Replacing preview with information about flighted roll outs

---

docs/develop/external-calls.md
docs/develop/power-automate-integration.md
docs/develop/typescript-restrictions.md
docs/resources/scenarios/noaa-data-fetch.md
licensing-information.md

Objects can be returned by scripts in PA flows as long as they are composed of basic types.

[Power Automate] (Parameters and returns) Clarifying support of returned objects

---

docs/resources/samples/excel-samples.md

[excel] (Samples) Giving NOW() link context in date sample

---

docs/develop/macros-power-automate.md
docs/toc.yml

[Power Automate] (.xlsm files) Better clarify .xlsm support story and motivation

---

docs/resources/samples/get-table-data.md

Fixes #498.
Based on a solution from @yutao-huang.

[excel] (Samples) Fix implicit any error in JSON sample

---

docs/resources/samples/excel-cross-reference.md

Fixes #502.
There was a missing value from the list for one of the Power Automate connector blocks. I also took the opportunity to clarify what the dynamic values are, since PA labels them in a similar way.

[excel] (Samples) Add clarity to Power Automate steps around script return values

---

docs/resources/samples/samples-overview.md

This is based on a customer verbatim around not finding the Automate tab after starting one of the samples.

[excel] (Samples) Make prerequisite note more prominent

---

docs/resources/samples/excel-samples.md

Fixes #511.
This sample finds all the cells with a formula in the current worksheet. It then replaces those cells with their current value, overwriting the formulas in the process.

[excel] (Formulas) Adding a formula-to-value sample

---

docs/resources/samples/clear-table-filter-for-active-cell.md
docs/resources/samples/samples-overview.md
docs/toc.yml

This PR restores a sample to the TOC and samples list. I believe it was overlooked during this initial sample migration.

[excel] (Samples) Adding clear table filter sample to TOC and sample list

---

docs/testing/troubleshooting.md

If EWS is disabled, SP scripts aren't displayed in the gallery as "most recent" scripts. This note publicly documents this issue.

[excel] (SharePoint) Add note about recent SP script bug

---

docs/resources/samples/get-table-data.md

We had an anonymous customer say this error returned errors. I verified the code and everything is working as expected. Updating the ms.date to reflect that we've looked at the content recently.

[admin] (Freshness) Updating date after verifying sample

---

docs/overview/code-editor-environment.md

Based on feedback in a previous PR, I'm adding a note to the Code Editor article promoting the VS Code offering.

[excel] (Code Editor) Adding cross-linking note for VS Code

---

docs/testing/platform-limits.md

[Power Automate] (Limitations) Add parameter size limit

---

docs/resources/power-query-differences.md
docs/tutorials/excel-tutorial.md

This is in response to a recent Stack Overflow confusion about not finding the Action Recorder in Excel on Windows.

[excel] (Tutorial) Make it more obvious you need to start on Excel on the web

---

docs/includes/platform-requirements.md
docs/overview/excel.md
docs/testing/platform-limits.md

The [Platform limts](https://learn.microsoft.com/en-us/office/dev/scripts/testing/platform-limits) article has a high bounce rate. My hypothesis is that people come here searching for what platforms support the feature. This PR adds that information to that page.

[excel] (Platform) Add platform support to platform limits article

---

docs/includes/platform-support-table.md
docs/resources/add-ins-differences.md
docs/resources/vba-differences.md

Updating this support table based on the feedback in #576.

[excel] (Other extensibility platforms) Update support table to show web and COM add-ins

---

docs/includes/platform-requirements.md
docs/overview/script-storage.md

This PR outlines the online requirement Office Scripts has as a connected service.

[excel] (Requirements) Adding notes about internet connectivity requirements

---

docs/develop/best-practices.md
docs/develop/external-calls.md
docs/includes/platform-requirements.md
docs/includes/platform-support-table.md
docs/overview/excel.md
docs/resources/power-query-differences.md
docs/tutorials/excel-tutorial.md

The Action Recorder will be generally available on Windows and Mac. This PR updates the documentation to no longer imply otherwise.

[excel] (Action Recorder) Action Recorder is supported on Windows and Mac

---

docs/resources/vba-differences.md

This note is based on customer feedback to better clarify that someone without a commercial license will need to keep using VBA for personal automation solutions.

[excel] (VBA Differences) Adding note about scripts requiring licenses

---

docs/includes/platform-requirements.md
docs/overview/excel.md

Fixes #599.
This PR adds a note about the gradual rollout of the action recorder.

[excel] (Action Recorder) Add action recorder rollout note

---

docs/includes/platform-requirements.md
docs/overview/excel.md
docs/testing/platform-limits.md

The Action Recorder is GA everywhere except the Semi-Annual channel. This PR updates the requirements note accordingly.

[excel] (Action Recorder) Update recorder availability note

---

docs/develop/use-json.md

Based on customer feedback, we're adding instructions on how to use a `fetch` `POST` command from a script.

[excel] (External Calls) Adding fetch post sample

---

docs/develop/external-calls.md
docs/includes/external-calls-power-automate.md
docs/includes/platform-requirements.md
docs/resources/samples/add-image-to-workbook.md
docs/testing/platform-limits.md
docs/testing/power-automate-troubleshooting.md

Fixes #610.
This PR reorganizes some of the PA troubleshooting content. The idea is that the "limits" article should have everything that didn't supported, while the "troubleshooting" article should contain errors that might crop up while making a potentially valid flow.

[excel] (Power Automate) Reorganize Power Automate limits about external calls

---

docs/develop/external-calls.md
docs/resources/samples/add-image-to-workbook.md

Fixes #614.
This PR makes it clearer that the sample in question doesn't work with local files. It also increases the discoverability of external call samples by expanding a list in the external call article.

[excel] (Images) Add note about local file compatibility

---

docs/develop/power-automate-integration.md
docs/overview/script-storage.md

[Internal work item](https://office.visualstudio.com/OC/_workitems/edit/7963176)

[excel] (Power Automate) Add run script from SharePoint note

---

docs/develop/user-input.md

This feature is coming to limited preview on the web first. This PR adjusts the note to reflect that.

[excel] (Parameters) Add preview note

---

docs/overview/script-storage.md

Per internal request, will send bug link internally.

[excel] (Storage) Remove Ran script directions

---

docs/overview/script-storage.md
docs/testing/platform-limits.md
docs/testing/power-automate-troubleshooting.md
docs/testing/troubleshooting.md

This PR documents the effects of Conditional Access on Office Script. Mainly, that they won't work from unmanaged devices if those policies are in place.

[excel] (File storage) Conditional Access policies and Office Scripts

---

docs/develop/user-input.md

Feature support has been flighted for 100%, so the docs should reflect this support.

[excel] (User Input) Parameters supported in Excel on the web

---

docs/testing/power-automate-troubleshooting.md

[excel] (Power Automate) Note PowerBI source refresh

---

docs/develop/power-automate-integration.md
docs/testing/platform-limits.md

Updating the docs to include this best practice.

[excel] (Power Automate) Add best practice of blocking unmanaged devices

---

docs/testing/power-automate-troubleshooting.md

Remove obsolete table line

---

docs/testing/power-automate-troubleshooting.md

Fixes https://github.com/OfficeDev/office-scripts-docs/issues/657

[excel] (Power Automate) Clarify Workbook.refreshAllDataConnections behavior

---

docs/resources/samples/table-samples.md

Fixes #666.
This PR adds a sample that demonstrates how to filter out a single value from a table.

[excel] (Table) Add an exclusive value table filter sample

---

docs/testing/platform-limits.md

[excel] (GCC) Adding note about GCC High

---

docs/index.md

This PR adds some popular samples to the front page in the hopes helping users looking to start from sample code.

[excel] (Landing page) Add samples to index page

---

docs/overview/excel.md
docs/resources/samples/samples-overview.md
docs/testing/platform-limits.md
docs/testing/troubleshooting.md

The list of platform requirements was occupying a lot of page real estate. This PR helps streamline the introductory reading experience.

[excel] (Overview) Link to platform requirements instead of listing them in the intro page

---

docs/includes/platform-requirements.md

This Record Actions button is fully available in Enterprise builds: https://learn.microsoft.com/en-us/officeupdates/semi-annual-enterprise-channel#excel. This PR removes the note about needing that build for full functionality.

[excel] (Action Recorder) Remove SA channel note

---

docs/develop/power-automate-integration.md
docs/includes/platform-requirements.md
docs/includes/power-automate-needs-business.md
docs/testing/platform-limits.md
docs/testing/power-automate-troubleshooting.md

The [Office 365 Enterprise E1 and Office 365 F3](https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-plan-options) SKUs will soon support Office Scripts. This PR updates the requirement lists to make that clear, as well as define the PA support.

[excel] (Licensing) Add information about F3/E1 support

---

docs/resources/samples/write-large-dataset.md

[excel] (Samples) Fix typo describing the write script as a read operation

---

docs/includes/platform-requirements.md

While Scripts for home and family are in preview, users will need to join the M365 Insider program.

[excel] (Licensing) Add step to join Insiders for personal scripts

---

docs/resources/samples/automate-tasks-on-all-excel-files-in-folder.md
docs/resources/samples/convert-csv.md
docs/resources/samples/email-images-chart-table.md
docs/resources/samples/excel-cross-reference.md
docs/resources/samples/report-day-to-day-changes.md
docs/resources/samples/write-large-dataset.md

In #726, it was pointed out that folks coming from Power Automate who are new to Scripts would be unfamiliar with saving scripts in the Code Editor.  This PR adds text to all the flow-based samples to point out readers should open Excel and use the Code Editor.

[excel] (Samples) Add mention of opening code editor to save scripts in PA samples

---

docs/develop/web-client-performance.md

Based on some anonymous feedback given through the page feedback controls, the reason for changing the calculation mode is unclear. This PR adds a section to the performance article explaining why you'd use this.

[excel] (Performance) Add section about manual recalculations to perf article

---

docs/develop/macros-power-automate.md

We had some customer confusion about the scope of .xlsm file support. This PR hopes to clarify that.

[excel] (Power Automate) Clarify .xlsm file behavior and scope

---

docs/overview/excel.md
docs/resources/samples/combine-worksheets-into-single-workbook.md
docs/testing/platform-limits.md
docs/testing/undo.md

Also clean up support.microsoft.com links

[Admin] Remove support.office.com links

---

Contributing.md

Matching some of the edits in this PR: https://github.com/OfficeDev/office-js-docs-pr/pull/4730

[admin] (Contributing) Minor edits to contributor file

---

docs/tutorials/excel-tutorial.md

This PR refreshes the table tutorial per August low engagement results.

[excel] (Tutorial) Refresh create a table tutorial

---

docs/overview/excel.md

Replacing deprecated Red Tiger video embeds with migrated Learn Videos. Point of contact: @meganbradley
DocuTune v1.5.2.0
CorrelationId: [ac50b370-fbb9-4fcc-b22d-306bf6bf2281](https://github.com/OfficeDev/office-scripts-docs/pulls?q=is%3Apr+ac50b370-fbb9-4fcc-b22d-306bf6bf2281+)
#docutune

[BULK] - DocuTune remediation - Red Tiger deprecation 

---

.openpublishing.publish.config.json

Fix fusion TOC (#793)
