docs/tutorials/excel-tutorial.md

This addresses two issues with the tutorial:
- There was an inconsistency in the number format for the credit statement example.
- The get and set commands around the absolute value calls have been split into two lines to increase readability.

Clean up tutorial

---

docs/index.md
docs/resources/excel-samples.md
docs/testing/undo.md
docs/tutorials/excel-tutorial.md

According to the CATS report, the descriptions for these pages were not of sufficient length. They have been adjusted accordingly.

Improve metadata descriptions

---

docs/develop/power-automate-integration.md

Office Scripts can't be run through shared Power Automate flows. This PR adds documentation to that effect.

Adding shared flow note

---

docs/develop/javascript-objects.md
docs/overview/code-editor-environment.md

Office Scripts don't support calls to external libraries. This PR makes that clear to developers.

Adding notes about external libraries

---

.openpublishing.publish.config.json

The necessary changes for the conceptual repo to orchestrate monikers in the reference docs. See https://github.com/OfficeDev/office-scripts-docs-reference/pull/30 for the corresponding changes.

Conceptual-side monikers

---

docs/tutorials/excel-read-tutorial.md
docs/tutorials/excel-tutorial.md

This PR switches the two Office Scripts tutorials to the sync API. It also removes references in the text to `load` and `sync`.
Please note that this is being merged into the `Sync` staging branch.

Switching the tutorials to use the sync API

---

docs/develop/power-automate-integration.md
docs/tutorials/excel-power-automate-manual.md
docs/tutorials/excel-power-automate-trigger.md

Since the sync APIs have reached MSIT, it seemed prudent to modernize the Power Automate content. This updates the tutorials and the content around params and returns (to remove references to Promises).

Update PA content with Sync code

---

docs/develop/scripting-fundamentals.md

Adding this note to be more upfront about the possibility a customer's script is async. This gives them a quick way to identify the model and refers them to tools to help.

Adding a cautionary note about the async model

---

docs/develop/power-automate-integration.md
docs/tutorials/excel-power-automate-manual.md
docs/tutorials/excel-power-automate-trigger.md

Power Automate does not automatically update the schema for an Office Script in the connector when the script is changed. If the script has its parameters or return type changed, the flow block needs to be updated.

Reminder to update the flow block when changing param/return types

---

docs/develop/external-calls.md
docs/overview/excel.md

Cross-linking to the OneDrive docs to help answer questions about what happens to a user's scripts when they depart the company. 
Also fixing an old admin link.

Linking to OneDrive retention policy

---

docs/resources/vba-differences.md

Office Scripts don't have events, like VBA macros do. This PR adds a statement to that effect in the VBA vs. Scripts doc.
Review site link: https://review.docs.microsoft.com/en-us/office/dev/scripts/resources/vba-differences?branch=AlexJ-EventNote

Adding note about events

---

docs/tutorials/excel-read-tutorial.md
docs/tutorials/excel-tutorial.md

Fixes #205. 
This PR addresses the recent change from `getValue` returning `any` to a `number | string | boolean`. It also adds a note explaining why the cast is needed.

Add number casts to tutorial

---

docs/testing/power-automate-troubleshooting.md

The `activate` method works in Power Automate, but does not have the typical UI-centric effect it's in-client usage would.

Add information about Worksheet.activate

---

docs/develop/typescript-restrictions.md

This documents the linter restriction in Office Scripts around arrow functions.

Adding restriction about arrow functions

---

docs/develop/external-calls.md
docs/resources/samples/external-fetch-calls.md

The `any` type is not allowed in Office Scripts. As such, JSON data returned by `fetchResult.json()` needs to be assigned to a type. This type needs to be defined in the script as an interface with matching properties.

[external calls] (fetch) Specify that fetched JSON data needs a type

---

docs/tutorials/excel-tutorial.md

I'm adding this line to help ease a user's frustration if they start the tutorial without having the Automate tab accessible. I don't think it detracts from the tutorial, but I'm open to feedback.

Adding further troubleshooting advice in the tutorial

---

docs/overview/code-editor-environment.md

Merging the IntelliSense information from https://github.com/OfficeDev/office-scripts-docs/pull/248 into the Code Editor environment overview.

[Code Editor] Adding IntelliSense tips

---

docs/overview/script-storage.md

Fixes #280.
This PR adds a section about script file recovery. Mostly, it links to the OneDrive steps for this, but it adds some details about script behavior after recovery.

[storage] Adding a section about recovering osts files

---

docs/develop/scripting-fundamentals.md
docs/index.md
docs/overview/excel.md

Hi @AlexJerabek, I noted there were no links to the Office Scripts dev portal in the docs so I added a couple. Let me know if there are other "See also" sections or other places in the docs we can add the link:
- [Office Scripts Dev Center](https://developer.microsoft.com/office-scripts)
Also, changed link from Stack Overflow to Microsoft Q&A office-scripts-excel-dev tag.

add link to dev portal

---

docs/develop/typescript-restrictions.md

[Internal work item](https://office.visualstudio.com/OC/_workitems/edit/5125498?src=WorkItemMention&src-action=artifact_link)
[Review site](https://review.docs.microsoft.com/en-us/office/dev/scripts/develop/typescript-restrictions?branch=AlexJ-Unions#unions-of-excelscript-types-and-user-defined-types-arent-supported)
The union of `ExcelScript` types and user-defined types is not supported. This causes problems with the transpiler that handles the async workbook communication. This PR updates the TypeScript Limitations page to include information about this problem.

[typescript] (Restrictions) Clarifying union type support

---

Issue_Template.md
README.md
docs/docfx.json
docs/index.md
docs/testing/troubleshooting.md

Fixes #397. 
The current guidance is to submit feature requests through the Code Editor's feedback button. This PR removes the obsolete UserVoice links and replaces them with guidance to use the feedback button.

[support] (Feature Requests) Remove references to UserVoice

---

.gitignore
docs/develop/power-automate-integration.md
docs/testing/power-automate-troubleshooting.md

Fixes #416.
This PR clarifies the distinction between the Array object and arrays (`x[]` versus `Array<X>`) necessary for the PA connector. It also adds some common errors to the PA troubleshooting section.
Tagging @jeremy-msft for technical accuracy and @alison-mk for content.

[Power Automate] (Parameters and returns)  Addressing feedback about PA return types

---

docs/resources/samples/convert-csv.md

Fixes #417.
If the user's CSV data is in an irregular shape, this script doesn't work. To help customers adopt the sample into their own code, I've explained the error message they'll get and added an alternate version of the script.
Note to reviewers, if you want to quickly test the script, replace the line `csv = csv.trim();` with `csv = "x,y,z\r\nd,r";`

[samples] (CSV Parsing) Adding error text and alternate script

---

docs/develop/typescript-restrictions.md

[Internal work item](https://office.visualstudio.com/OC/_workitems/edit/5165026/)
APIs that use async/await statements in the transpiled script can't be called in constructors. This PR documents that limitation.

[typescript] (Limitations) Add limitation about constructors

---

Issue_Template.md
README.md
docs/docfx.json
docs/testing/troubleshooting.md

Based on [this internal Code Editor change](https://office.visualstudio.com/OC/_git/MakerCodeEditor/pullrequest/1077863), the **Send Feedback** button has been removed. This PR updates the docs accordingly.
@nancy-wang, do we have an alternate way to capture feedback and feature requests?

[ux] (Code Editor) Removing references to the Code Editor feedback button

---

docs/resources/scenarios/analyze-web-downloads.md

Fixes #436.
When [this restriction](https://docs.microsoft.com/en-us/office/dev/scripts/develop/typescript-restrictions#no-any-type-in-office-scripts) was added to Office Scripts, the sample in question was not updated to match.
Some of the code spacing is also updated to reflect the current spacing standards in the Code Editor.

[samples] (Scenarios) Fix implicit any usage in the Analyze web downloads sample

---

docs/testing/platform-limits.md

Fixes #440.
This PR adds a callout for the 120-second timeout that occurs with PA actions.

[Power Automate] (Limits) Adding note about PA timeouts

---

docs/overview/excel.md

This PR removes the "preview" markings for the script button feature. It does leave the Windows rollout information in place, since that is not at 100% yet.

[script buttons] (Rollout status) Removing preview text for script buttons

---

docs/resources/samples/convert-csv.md

Fixes #461.
This fix allows for the first cell in a CSV string to be blank.
Note to reviews: You can avoid making the whole flow and just test the scripts by adding this line to the being of the script:
```
csv = `,3,1,2\r\n2,,5,6\r\n,6,4,3`;
```

[samples] (CSV) CSV parser can detect first-row blank cells

---

docs/develop/script-buttons.md
docs/overview/excel.md

There's not a formal title on the page that loads in the task pane when you select a script. Based on that, the term "details" shouldn't be capitalized.

[excel] (Task pane) Standardize capitalization for script details page

---

Issue_Template.md
README.md
docs/develop/power-automate-integration.md
docs/develop/script-buttons.md
docs/develop/scripting-fundamentals.md
docs/index.md
docs/overview/excel.md
docs/resources/add-ins-differences.md
docs/resources/samples/excel-samples.md
docs/resources/vba-differences.md
docs/toc.yml
docs/tutorials/excel-read-tutorial.md
docs/tutorials/excel-tutorial.md

The Action Recorder and Code Editor are still only found in Excel on the web. However, scripts can be run on Windows using script buttons. There's also an inherent lack of a platform when talking about Power Automate. So, this PR hopes to rationalize that across the docs without giving a false impression that Excel on the web isn't a fundamental part of the scripting experience.
Additionally, this PR adds content about Windows/web API support. Effectively, APIs in the [online-only](https://docs.microsoft.com/en-us/javascript/api/requirement-sets/excel/excel-api-online-requirement-set?view=excel-js-preview) requirement set cause button-based scripts not to run on Windows. However, the sync API transpilation story makes that complicated to explain.

[excel] (Platform) Generalizing language to better account for Script Buttons

---

docs/resources/samples/excel-samples.md

As part of my intern project on Storage & Intelligence, I've created two new samples that will be present in the Samples tab for Office Scripts. Alex Jerabek requested that these samples also be added to the documentation to increase sample code coverage.

Samples for unhide all rows/cols and freeze selection to excel-sampes

---

docs/resources/samples/excel-samples.md

Previous PR was missing ticks to close a TypeScript block, resulting in the following section being included as code in the previous section. Added ``` to close first example and corrected Typescript to TypeScript.

Adding Missing ``` to TypeScript block.

---

docs/overview/script-storage.md

SharePoint support for Office Scripts should be generally available for all users for Ecel on the web. This PR removes the note that says otherwise.

[ownership] (SharePoint) Remove flighting note for team ownership

---

docs/testing/platform-limits.md

To help with general discoverability, I want to link to this support article. It should help our users find a more complete list of Excel limitations.
I'm also removing the "See also" link to the fundamentals article to help curate that list to the most useful follow-up articles.

[excel] (Platform limits) Adding cross link to base Excel limits articles

---

docs/includes/platform-requirements.md
docs/overview/excel.md
docs/testing/platform-limits.md

This PR is in response to #585. It highlights that the Action Recorder is a web-only feature in the two places we talk about platform support.

[excel] (Action Recorder) Updating support note to clarify Action Recorder is web-only

---

docs/testing/power-automate-troubleshooting.md

This PR updates the PA troubleshooting article to mention strict Open XML workbooks aren't supported in flows.
Quick note to the writer reviewer, I used the casing found in [this article](https://learn.microsoft.com/en-us/DeployOffice/compat/office-file-format-reference). Happy to change if you have a better source.

[excel] (Power Automate) ISO strict Open XML note

---

docs/develop/power-automate-integration.md

Fixes #623.
This PR aims to make the OneDrive script location limitation in Power Automate clearer.

[excel] (Power Automate) Clarify script storage limitations in PA integration article

---

docs/docfx.json

The original link is redirecting to the new one. Do suggest a more appropriate URL if you have one.

Refine product feedback link

---

docs/develop/best-practices.md
docs/develop/pivottables.md
docs/develop/power-automate-integration.md
docs/develop/power-automate-parameters-returns.md
docs/develop/scripting-fundamentals.md
docs/index.md
docs/resources/samples/count-blank-rows.md
docs/resources/samples/range-samples.md
docs/resources/vba-differences.md
docs/toc.yml
docs/tutorials/excel-power-automate-manual.md
docs/tutorials/excel-power-automate-returns.md
docs/tutorials/excel-power-automate-trigger.md
docs/tutorials/excel-read-tutorial.md
docs/tutorials/excel-tutorial.md

In an effort to drive tutorial usage, this PR adjusts the titles of the tutorial to focus on the task being achieved, rather than the skill being taught.
This PR also adjusts some of the language in the tutorials to focus on the reader, not the author ("you" instead of "we").

[excel] (Tutorials) Convert tutorial titles to reflect scenarios instead of features

---

docs/index.md
docs/resources/samples/add-excel-comments.md
docs/resources/samples/range-samples.md
docs/resources/samples/samples-overview.md
docs/toc.yml

This PR adjusts the sample list and TOC to better delineate between types of samples. Most significantly, the Power Automate samples are separated so they're easier to find.

[excel] (Samples) Adjust how the samples and scenarios are branded

---

docs/resources/samples/convert-csv.md

This PR is based on a customer concern that accented characters are converted to invalid characters in this sample. The solution is to properly encode the .csv files.
Shout out to this [PA forum post](https://powerusers.microsoft.com/t5/Building-Flows/Create-a-csv-file-that-uses-UTF-8-character-encoding/m-p/1311587/highlight/true#M148980) for the solution!

[excel] (CSV) Add note about fancy characters

---

docs/develop/pivottables.md

This PR aims to explain how users change how data fields in PivotTables are displayed. It highlights the `setShowAs` and `setSummarizeBy` methods.

[excel] (PivotTable) Add summary and field value section to PivotTable article

---

docs/includes/platform-support-table.md

Fixes #743.
COM add-ins are not supported on Mac, so this table is misleading.
Tagging @davidchesnut for a sanity check.

[all] (support) Remove mention of COM support for Mac

---

docs/includes/platform-requirements.md

E1 licenses are web-only, so this SKU clarification is obsolete.

[excel] (Support) Remove comment about Scripts requiring SKUs with desktop apps

---

docs/develop/script-buttons.md

This PR clarifies some behavior about script buttons. The feature relies on OneDrive file sharing, meaning that organizational policies may block the feature and that the feature is not available in consumer SKUs.

[excel] (Script buttons) Add note about OneDrive sharing for buttons

---

docs/resources/samples/table-samples.md

Removing inaccurate code snippet per customer issue: https://github.com/OfficeDev/office-scripts-docs/issues/758
Will add new section about how to copy a filtered table in separate PR.

[excel] (Table) Remove copyFrom tip due to inaccuracy

---

docs/overview/excel.md
docs/toc.yml

The goal of this PR is to make the samples more discoverable. It does three things: 
- Moves the Samples node above Troubleshooting 
- Sets the TOC node "Office Scripts in Excel" to always be expanded 
- Sets the "Samples" node to always be expanded -- curious about feedback on this one

[excel] (TOC) Move samples node

---

docs/overview/script-storage.md

[excel] (Storage) Update storage location for local to OneDrive migration (#783)
* [excel] (Storage) Update storage location for local to OneDrive migration
* Undo share scripts change
* Incorporate eng feedback
* Update docs/overview/script-storage.md
---------

[admin] Publish

---

docs/resources/samples/copy-tables-combine.md

I checked this sample after a customer report. Seems to be working fine. This PR updates the date to reflect the recent approval, as well as does a quick style pass.

[Excel] (Tables) Refresh table combination sample
